In [71]:
num=2.5
type(num)

float

In [5]:
num=9+8j
type(num)

complex

In [7]:
a=5.6
b=int(a)
type(a)


float

In [8]:
k=float(b)
type(k)

float

In [10]:
a=True
type(a)


bool

In [9]:
c=complex(2,3)
type(c)

complex

In [13]:
bool=2>1
True
type(bool)

bool

In [14]:
list[2,3,4,5]
type(list)

type

In [15]:
p=(2,3,4,5)
type(p)

tuple

In [16]:
d={2,3,2,4,5,6}
type(d)

set

In [17]:
str="hiiii"
type(str)

str

In [18]:
str="a"
type(str)

str

In [19]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
tuple(range(2,10,2))

(2, 4, 6, 8)

In [21]:
d={1:'a',2:'b',3:'c'}
type(d)

dict

In [10]:
d={'siddu':'redmi','ratan':'samsung','amkith':'iphone'}
d.values()
d.keys()
d.get('siddu')
d['ratan']

'samsung'

In [4]:
x=4
y=3
x+=2
b=2
b=-b
print(x+y)
print(x/y)
print(b)

9
2.0
-2


In [42]:
a=3
b=3
a<b
a==b
a<=b
a>=b
a!=b

False

In [5]:
a=6
b=4
a<3 and b<4
a<3 or b<3
x=True
not x

False

In [6]:
bin(35)
0b11001
oct(25)
hex(10)
0xf
bin(65)

'0b1000001'

In [66]:
~12
~45
~121
12 & 13
12|13
12^13
25^30
10<<2
10>>2

2

In [68]:
a=int(input("enter the value of a "))
b=int(input("enter the value of b "))
c=a+b
print("sum is : ",c)

enter the value of a 1
enter the value of b 2
sum is :  3


In [69]:
ch=input("enter a charector")[0]
print(ch)

enter a charectordhanya
d


In [70]:
res=eval(input("enter an expression "))
print(res)

enter an expression 2+3-3
2


In [7]:
nums=[1,2,3,4,5]
nums[0]
nums[1:]
nums[-5]
names=['siddu','ratan','ankith']
names
values=[2.3,'siddu',21]
values
dha=[nums,names]
dha
nums.insert(3,22)
nums
nums.remove(22)
nums
nums.pop(1)
nums
del nums[1:]
nums
nums.extend([21,2,4,5])
nums
min(nums)
max(nums)
sum(nums)
nums.sort()
nums

[1, 2, 4, 5, 21]

In [33]:
tup=(1,2,3,4,5)
tup
d={22,1,2,4,5}
d
nums=[25,36,95,14,12,26]
del nums[2:5]
nums

[25, 36, 26]

In [8]:
data={1:'siddu',2:'ratan',5:'ankith'}
data
data[1]
data.get(2)
data.get(4)
print(data.get(4))
data.get(3,'not found')
keys=['siddu','ratan','ankith']
values=['pyhton','java','c']
data=dict(zip(keys,values))
data
data['punu']='cs'
data

None


{'siddu': 'pyhton', 'ratan': 'java', 'ankith': 'c', 'punu': 'cs'}

In [48]:
prog={'js':'atom','cs':'vs','python':['pycharm','subline'],'java':{'jse':'netbeans','jee':'eclipse'}}
prog
prog['js']
prog['python'][1]
prog['java']['jee']

'eclipse'

In [6]:
x=5
y=x%2

if y==0:
    print("even")
    
else:
    print("odd")
print("byte")
    


odd
byte


In [10]:
x=5
if x==1:
    print("one")
elif x==2:
    print("two")
elif x==3:
    print("three")
elif x==4:
    print("four")
else :
    print("long input")

long input


In [9]:
i=1
while i<=5:
    print("siddu ",end="")
    j=1
    while j<=4:
        print("rocks ",end="")
        j=j+1
        
    i=i+1
    print()

siddu rocks rocks rocks rocks 
siddu rocks rocks rocks rocks 
siddu rocks rocks rocks rocks 
siddu rocks rocks rocks rocks 
siddu rocks rocks rocks rocks 


In [11]:
x=['siddu',2.3,1]
for i in x:
    print(i)


siddu
2.3
1


In [22]:
for i in range(1,10):
    if i%3==0 or i%5==0:
        continue
        
    print(i)
    
print("bye")

1
2
4
7
8
bye


In [24]:
for i in range(1,10):
    if(i%2!=0):
        pass
    else:
        print(i)
print("bye")

2
4
6
8
bye


In [4]:
from array import *
val=array('i',[1,2,3,4,5])
newArr=array(val.typecode,(a*a*a for a in val))
for e in newArr:
     print(e)

1
8
27
64
125


In [10]:
from array import * 
arr=array('i',[])
n=int(input('enter the length of array'))
for i in range(n):
    x=int(input("enter the next values"))
    arr.append(x)
print(arr)
val=int(input("enter the value to search"))
k=0
for e in arr:
    if e==val:
        print(k)
        break
    k+=1

enter the length of array3
enter the next values1
enter the next values2
enter the next values3
array('i', [1, 2, 3])
enter the value to search3
2


In [13]:
from numpy import *
arr=array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [22]:
from numpy import *
arr=linspace(0,15,20)
ar=arange(1,15,2)
a=logspace(1,40,5)
arra=zeros(5)
array=ones(5)
print(array)

[1. 1. 1. 1. 1.]


In [25]:
from numpy import *
arr1=array([1,3,4,5,6])
arr2=array([1,3,4,5,6])
arr3=arr1+arr2
print(sum(arr1))
print(concatenate([arr1,arr2]))


19
[1 3 4 5 6 1 3 4 5 6]


In [3]:
from numpy import *
arr1=array([1,2,3,4,5])
arr2=arr1.view()
print(id(arr1))
print(id(arr2))

2207777692656
2207777693712


In [17]:
from numpy import *
arr1=array([[1,2,3,6,3,4],
           [4,5,6,2,4,5]])
arr2=arr1.flatten()
arr3=arr2.reshape(2,2,3)
print(arr3)

[[[1 2 3]
  [6 3 4]]

 [[4 5 6]
  [2 4 5]]]


In [25]:
arr1=array([[1,2,3,6],
           [4,5,6,2]])
m1=matrix('1 2 3; 4 4 5 ;6 7 4')
m2=matrix('1 2 3; 4 4 5 ;6 7 4')
print(diagonal(m))
print(m.min())
print(m.max())
m3=m1*m2;
print(m3)

[1 4 4]
1
7
[[27 31 25]
 [50 59 52]
 [58 68 69]]


In [35]:
def greet():
    print("hello")
    print("good morning")
def add_sub(x,y):
    c=x+y
    d=x-y
    return c,d
result1,result2=add_sub(2,3)
print(result1,result2)

5 -1


In [43]:
def update(x):
    print(id(x))
    x[1]=8
    print(id(x))
    print('x',x)
x=[10,20,30]
print(id(x))
update(x)
print('a',x)

2207812042944
2207812042944
2207812042944
x [10, 8, 30]
a [10, 8, 30]


In [12]:
def person(name,age=20):
    print(name)
    print(age)
person('siddu')

siddu
20


In [52]:
def sum(*b):
    c=a
    for i in b:
        c=c+1
    print(c)
sum(2,3,4,2)

14


In [14]:
def person(name,**data):
    print(name)
    print(data)
person('siddu',age=21,city='shimogga',mob=2334566)

siddu
{'age': 21, 'city': 'shimogga', 'mob': 2334566}


In [71]:
a=9
def something():
    global a
    a=15
    print(id(x))
    print('in fun',a)
something()
print('outside',a)


2207812042944
in fun 15
outside 15


In [78]:
def count(lst):
    even=0
    odd=0
    for i in lst:
        if i%2==0:
            even+=1
            
        else:
            odd+=1
    return even,odd

lst=[1,2,3,4,5,6]
even,odd=count(lst)
print('even : {} and odd :{}'.format(even,odd))


even : 3 and odd :3


In [87]:
import sys
sys.setrecursionlimit(100)
print(sys.getrecursionlimit())
i=0
def greet():
    global i
    i+=1
    print("hello",i)
    greet()
greet()

100
hello 1
hello 2
hello 3
hello 4
hello 5
hello 6
hello 7
hello 8
hello 9
hello 10
hello 11
hello 12
hello 13
hello 14
hello 15
hello 16
hello 17
hello 18
hello 19
hello 20
hello 21
hello 22
hello 23
hello 24
hello 25
hello 26
hello 27
hello 28
hello 29
hello 30
hello 31
hello 32
hello 33
hello 34
hello 35
hello 36
hello 37
hello 38
hello 39
hello 40
hello 41
hello 42
hello 43
hello 44
hello 45
hello 46
hello 47
hello 48
hello 49
hello 50
hello 51
hello 52
hello 53
hello 54
hello 55
hello 56
hello 57
hello 58
hello 59
hello 60
hello 61
hello 62
hello 63
hello 64
hello 65
hello 66
hello 67
hello 68
hello 69
Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13008\910599268.py", line 10, in <module>
    greet()
  File "C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13008\910599268.py", line 9, in greet
    greet()
  File "C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13008\910599268.py", line 9, in greet
    greet()
  File "C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13008\910599268.py", line 9, in greet
    greet()
  [Previous line repeated 66 more times]
  File "C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13008\910599268.py", line 8, in greet
    print("hello",i)
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\ipykernel\iostream.py", line 550, in write
    is_child = not self._is_master_process()
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\ipykernel\iostream.py", line 438, in _is

In [91]:
f=lambda a,b:a+b
result=f(5,6)
print(result)

11


In [98]:

nums=[1,2,3,4,5,6,7]
evens=list(filter(lambda n:n%2==0,nums))
doubles=list(map(lambda n: n*2,evens))
print(doubles)

[4, 8, 12]


In [104]:
def div(a,b):
    print(a/b)
def smart_div(func):
    def inner(a,b):
        if a<b:
            a,b=b,a
        return func(a,b)
    return inner
div=smart_div(div)
div(2,4)

2.0


In [1]:
print(__name__)

__main__


In [ ]:
//module
//_name_  

In [115]:
class converter:
    def config(self):
        print("i5,16gb,1tb")
x=5
print(type(x))
a='g'
print(type(a))
com1=converter()
print(type(com1))


<class 'int'>
<class 'str'>
<class '__main__.converter'>


In [118]:
class computer:
    def config(self):
        print("i5,16gb,1tb")
com1=computer()
com2=converter()
computer.config(com1)
computer.config(com2)
com1.config()
com2.config()

i5,16gb,1tb
i5,16gb,1tb
i5,16gb,1tb
i5,16gb,1tb


In [2]:
class computer:
    def __init__(self,cpu,ram):
        self.cpu=cpu
        self.ram=ram
    def config(self):
        print("config is",self.cpu,self.ram)
com1=computer('i5',16)
com2=computer('python 3',0)

com1.config()
com2.config()

config is i5 16
config is python 3 0


In [17]:
class computer:
    def _init_(self):
        self.name="siddu"
        self.age=20
    def update(self):
        self.age=30
c1=computer()
c2=computer()
c1.name="ratan"
c1.age=12
c1.update()
print(c1.name)
print(c1.age)

ratan
30


In [18]:
class car:
    def _init_(self):
        self.mil=10
        self.com="rr"
c1=car()
c2=car()
c1.mil=5
print(c1.mil)


5


In [19]:
class student:
    student='evaluate'
    def __init__(self,n1,n2,n3):
        self.n1=n1
        self.n2=n2
        self.n3=n3
    def avg(self):
        return(self.n1+self.n2+self.n3)/3
    classmethod
    def getschool(cls):
        return cls.school
    staticmethod
    def info():
        print('this student cls in abc module' )
s1=student(35,36,38)
s2=student(35,36,38)
print(s1.avg)
print(student.getschool)
student.info()

<bound method student.avg of <__main__.student object at 0x0000024CA6584070>>
<function student.getschool at 0x0000024CA7F5C310>
this student cls in abc module


In [143]:
class A:
    def feature1(self):
        print("feature 1 working")
    def feature2(self):
        print("feature 2 working")
class B(A):
    def feature3(self):
        print("feature 3 working")
    def feature4(self):
        print("feature 4 working")
class c(B):
     def feature5(self):
        print("feature 5 working")
a1=A()
a1.feature1()
a1.feature2()


feature 1 working
feature 2 working


In [153]:
class A:
    def _init_(self):
        print('in A init')
    def feature1(self):
        print("feature 1 working")
    def feature2(self):
        print("feature 2 working")
class B(A):
    def _init_(self):
        super()._init_()
        print('in B init')
    def feature3(self):
        print("feature 3 working")
    def feature4(self):
        print("feature 4 working")

a1=A()
a1.feature1()

feature 1 working


In [1]:
a=5
b=3
print(a+b)


8


In [2]:
def topten():
    yield 1
    yield 2
    yield 3
values=topten()
print(values.__next__())
for i in values:
    print(i)
    


1
2
3


In [168]:
class Student:
    def _init_(self,m1,m2):
        self.m1=m1
        self.m2=m2
    def sum(self,a=None,b=None,c=None):
        s=0
        if a!=None and b!=None and c!=None:
            s=a+b+c
        elif a!=None and b!=None:
            s=a+b
        else: 
            s=a
        return s
s1=Student()
print(s1.sum(5,9))
    

14


In [171]:
class A:
    def show(self):
        print("in A show")
class B(A):
    def show(self):
        print("in B show")
a1=B()
a1.show()

in B show


In [176]:
a=2
b=0
try:
    print(a/b)
except Exception as e:
    print('cannot divide by zero',e)
finally:
    print('resource closed')

cannot divide by zero division by zero
resource closed


In [183]:
from time import sleep
from threading import *
class Hello(Thread):
    def run(self):
        for i in range(5):
            print("hello")
            sleep(1)
class Hii(Thread):
    def run(self):
        for i in range(5):
            print('hii')
            sleep(1)
t1=Hello()
t2=Hii()
t1.start()
sleep(0.2)
t2.start()

hello
hii
hello
hii
hello
hii
hello
hii
hello
hii
